// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

#include "news.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace test {
class FuckDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Fuck>
      _instance;
} _Fuck_default_instance_;
}  // namespace test
namespace protobuf_news_2eproto {
void InitDefaultsFuckImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::test::_Fuck_default_instance_;
    new (ptr) ::test::Fuck();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::Fuck::InitAsDefaultInstance();
}

void InitDefaultsFuck() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFuckImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Fuck, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Fuck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Fuck, mm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Fuck, m_str_),
  1,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::test::Fuck)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_Fuck_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "news.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\nnews.proto\022\004test\"!\n\004Fuck\022\n\n\002mm\030\001 \002(\005\022\r"
      "\n\005m_str\030\002 \002(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 53);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "news.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_news_2eproto
namespace test {

// ===================================================================

void Fuck::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Fuck::kMmFieldNumber;
const int Fuck::kMStrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Fuck::Fuck()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_news_2eproto::InitDefaultsFuck();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.Fuck)
}
Fuck::Fuck(const Fuck& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  m_str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_m_str()) {
    m_str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_str_);
  }
  mm_ = from.mm_;
  // @@protoc_insertion_point(copy_constructor:test.Fuck)
}

void Fuck::SharedCtor() {
  _cached_size_ = 0;
  m_str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mm_ = 0;
}

Fuck::~Fuck() {
  // @@protoc_insertion_point(destructor:test.Fuck)
  SharedDtor();
}

void Fuck::SharedDtor() {
  m_str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Fuck::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Fuck::descriptor() {
  ::protobuf_news_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_news_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Fuck& Fuck::default_instance() {
  ::protobuf_news_2eproto::InitDefaultsFuck();
  return *internal_default_instance();
}

Fuck* Fuck::New(::google::protobuf::Arena* arena) const {
  Fuck* n = new Fuck;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Fuck::Clear() {
// @@protoc_insertion_point(message_clear_start:test.Fuck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(!m_str_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*m_str_.UnsafeRawStringPointer())->clear();
  }
  mm_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Fuck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.Fuck)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 mm = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_mm();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mm_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string m_str = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_str()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->m_str().data(), static_cast<int>(this->m_str().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "test.Fuck.m_str");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.Fuck)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.Fuck)
  return false;
#undef DO_
}

void Fuck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.Fuck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 mm = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->mm(), output);
  }

  // required string m_str = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->m_str().data(), static_cast<int>(this->m_str().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Fuck.m_str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->m_str(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:test.Fuck)
}

::google::protobuf::uint8* Fuck::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.Fuck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 mm = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->mm(), target);
  }

  // required string m_str = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->m_str().data(), static_cast<int>(this->m_str().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Fuck.m_str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->m_str(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.Fuck)
  return target;
}

size_t Fuck::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:test.Fuck)
  size_t total_size = 0;

  if (has_m_str()) {
    // required string m_str = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_str());
  }

  if (has_mm()) {
    // required int32 mm = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mm());
  }

  return total_size;
}
size_t Fuck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.Fuck)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string m_str = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->m_str());

    // required int32 mm = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mm());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Fuck::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.Fuck)
  GOOGLE_DCHECK_NE(&from, this);
  const Fuck* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Fuck>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.Fuck)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.Fuck)
    MergeFrom(*source);
  }
}

void Fuck::MergeFrom(const Fuck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.Fuck)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_m_str();
      m_str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.m_str_);
    }
    if (cached_has_bits & 0x00000002u) {
      mm_ = from.mm_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Fuck::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.Fuck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Fuck::CopyFrom(const Fuck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.Fuck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fuck::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void Fuck::Swap(Fuck* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Fuck::InternalSwap(Fuck* other) {
  using std::swap;
  m_str_.Swap(&other->m_str_);
  swap(mm_, other->mm_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Fuck::GetMetadata() const {
  protobuf_news_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_news_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace test

// @@protoc_insertion_point(global_scope)
